### ISSUE TITLE
Could you please have a look here

### ISSUE THREAD

**Issue by Amraan-Amjad** [larsenv/Hoopla-Digital-Downloader#1]
Hello @larsenv 
I am a total noob to Python
Could you please tell me what to do here
I need to download a few audiobooks for my studies 
I hope you will help me : )

**Comment by Amraan-Amjad** [comment]
@larsenv 
Hello?

**Comment by larsenv** [comment]
What part are you currently stuck on? Sorry. I didn't see this until now

**Comment by Amraan-Amjad** [comment]
@larsenv 
Could you please help me here

**Comment by Amraan-Amjad** [comment]
![image](https://github.com/larsenv/Hoopla-Digital-Downloader/assets/121578485/90510bce-6ce4-436d-8d40-0bbe27688cb2)
This is what it is showing
Please tell me what am I doing wrong

**Comment by larsenv** [comment]
Unfortunately I'm not willing to help you over GitHub because you also need a CDM which requires addotional hard work to obtain. However, what I can do is grab em if you givs me the url of what you're interested in

**Comment by Amraan-Amjad** [comment]
> Unfortunately I'm not willing to help you over GitHub because you also need a CDM which requires addotional hard work to obtain. However, what I can do is grab em if you givs me the url of what you're interested in

Would you mind sharing any tutorials on YT or stuff like that
There are a whole bunch of MACAT books

**Comment by Amraan-Amjad** [comment]
If I could tweak the requirements file a bit
Would it still work?

**Comment by Amraan-Amjad** [comment]
![image](https://github.com/larsenv/Hoopla-Digital-Downloader/assets/121578485/e637a456-9f79-4c57-8092-37c6cc3f93b3)
![image](https://github.com/larsenv/Hoopla-Digital-Downloader/assets/121578485/f0abbd4f-8639-47b7-9268-7bd673eb0fb5)
Yeaaaaa!!
It downloaded
The main question is - Will it work?

**Comment by Amraan-Amjad** [comment]
One more question - How should I download the token
