### ISSUE TITLE
ModuleNotFoundError: No module named 'pywidevine.L3'

### ISSUE THREAD

**Issue by rmrf-sh** [larsenv/Hoopla-Digital-Downloader#2]
@larsenv 
L3 CDM created in /pywidevine/L3/cdm/devices/android_generic/
files are named 
`device_client_id_blob  device_private_key`

Error received when running command
`python3 hoopla-key.py https://www.hoopladigital.com/audiobook/harry-potter-and-the-sorcerers-stone-j-k-rowling/13280513 TOKEN REDACTED`

full error output:
```
Hoopla Digital Downloader by Larsenv

Traceback (most recent call last):
  File "/home/user/Development/Hoopla-Digital-Downloader/l3.py", line 15, in <module>
    from pywidevine.L3.cdm import cdm, deviceconfig
ModuleNotFoundError: No module named 'pywidevine.L3'
Traceback (most recent call last):
  File "/home/user/Development/Hoopla-Digital-Downloader/hoopla-key.py", line 84, in <module>
    print(url + ": " + title + ": " + "--key " + response.split("--key ")[1])
                                                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

```
Line 15 of l3.py is
`from pywidevine.L3.cdm import cdm, deviceconfig`

Environment information below
Fedora 35
Python 3.11 using a virtual environment, pip list below.
```
pip list
Package            Version
------------------ ----------
certifi            2023.11.17
charset-normalizer 3.3.2
click              8.1.7
construct          2.8.8
idna               3.6
pip                22.3.1
protobuf           3.20.0
pycryptodome       3.20.0
pymp4              1.4.0
pyperclip          1.8.2
pywidevine         1.8.0
PyYAML             6.0.1
requests           2.31.0
setuptools         65.5.1
Unidecode          1.3.7
urllib3            2.1.0
xmltodict          0.13.0
```

Other things to note:
The script errors after clone when installing the requirements :
```
ERROR: Cannot install -r requirements.txt (line 2) and protobuf==3.20.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested protobuf==3.20.0
    pywidevine 1.8.0 depends on protobuf<5.0.0 and >=4.25.1
    The user requested protobuf==3.20.0
    pywidevine 1.7.0 depends on protobuf<5.0.0 and >=4.24.4
    The user requested protobuf==3.20.0
    pywidevine 1.6.0 depends on protobuf==4.21.6
```
I ended up installing protobuf==3.20.0  after with the rest of the packages `pip install protobuf==3.20.0 `. Same error is given with the newest version of protobuf also.

Another note. Pyperclip is required by l3.py which I installed manually after getting the error 
`Hoopla-Digital-Downloader/l3.py", line 14, in <module>
    import pyperclip
ModuleNotFoundError: No module named 'pyperclip'`
Any help is greatly appreciated.

**Comment by larsenv** [comment]
I removed the requirement of having the L3 key as it now will grab it online
